services:
  - type: web
    name: ai-for-wise-guys
    runtime: node
    startCommand: npm run start
    buildCommand: npm install && npm run build
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_URL
        value: https://ai-for-wise-guys.onrender.com
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: NEXT_PUBLIC_SIMPLE_PRICE_ID
        sync: false
      - key: NEXT_PUBLIC_COMPLEX_PRICE_ID
        sync: false
